name: Upload Concrete Package
description: Uploads a Concrete CMS package to a server
inputs:
  username:
    description: 'Username for authentication'
    required: true
  password:
    description: 'Password for authentication'
    required: true
  packageFile:
    description: 'Path to the Concrete CMS package zip file'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
