name: Upload Concrete Package
description: Uploads a Concrete CMS package to a server
inputs:
  uuid:
    description: 'UUID of the Concrete CMS marketplace item'
    required: true
  username:
    description: 'Username for authentication'
    required: true
  password:
    description: 'Password for authentication'
    required: true
  packageFile:
    description: 'Path to the Concrete CMS package zip file'
    required: true
  versionNumber:
    description: 'Version Number of the package. (Fallback if empty: package controller)'
    required: false
  changelog:
    description: 'Changelog of the package. (Fallback if empty: scrap entry of CHANGELOG file)'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
